services:
  gateway:
    image: bwdesigngroup/ignition-docker:8.1.37
    environment:
      DEVELOPER_MODE: Y
      SYMLINK_GITIGNORE: false
      SYMLINK_THEMES: false
      SYMLINK_LOGBACK: false
      GATEWAY_SYSTEM_NAME: perspective-component-gateway
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: perspective-component.localtest.me
    volumes:
      - ../build/Example-Component-Library.modl:/modules/Example-Component-Library.modl
      - ./backups/gateway.gwbk:/restore.gwbk
    labels:
      traefik.enable: "true"
      traefik.hostname: "perspective-component"
    command: >
      -r /restore.gwbk
    networks:
      - default
      - proxy
    
networks:
  default:
  proxy:
    external: true
    name: proxy